### ISSUE TITLE
Not compatible with octomap 1.8

### ISSUE THREAD

**Issue by krontzo** [neka-nat/python-octomap#2]
Kudos for the wrapper.

Just wondering if you have any plans to update `python-octomap` to support the new API in `octomap` 1.8.0.

Working great!

**Comment by neka-nat** [comment]
Hi, krontzo.
I want to support octomap 1.8.0, but there are no small changes from 1.7 to 1.8.
I guess to begin the implementation by the end of this year.

Thank you.

**Comment by neka-nat** [comment]
Hi, krontzo.
python-octomap support v1.8.0.
Please try to work it.
