### ISSUE TITLE
cythoning error

### ISSUE THREAD

**Issue by proyan** [neka-nat/python-octomap#3]
Hi

I attempted to install the package and get an error when creating octomap.cpp

`Error compiling Cython file:
------------------------------------------------------------
...
        else:
            raise NullPointerException

    def dynamicEDT_update(self, updateRealDist):
        if self.edtptr:
            return self.edtptr.update(<cppbool?>updateRealDist)
                                    ^
------------------------------------------------------------

octomap/octomap.pyx:813:37: Cannot convert 'void' to Python object
`
I deleted the function dynamicEDT_update, and the everything built nicely. Any ideas what is going on? I am not versed in cython.

Thanks,
Rohan

**Comment by daizr** [comment]
@proyan hit this too, i think #4 fixes.
