### ISSUE TITLE
dynamicEDT3D error

### ISSUE THREAD

**Issue by maxtom** [neka-nat/python-octomap#7]
I build the package by using the comman:
`sudo python setup.py build_ext --include-dirs /opt/ros/indigo/include --library-dirs /opt/ros/indigo/lib
`

but the system error outputs:

skipping 'octomap/octomap.cpp' Cython extension (up-to-date)
building 'octomap' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include -I/usr/local/include -I/opt/ros/indio
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
octomap/octomap.cpp:461:44: fatal error: dynamicEDT3D/dynamicEDTOctomap.h: No such file or directory
 #include "dynamicEDT3D/dynamicEDTOctomap.h"
                                            ^
compilation terminated.

**Comment by neka-nat** [comment]
Hi maxtom.
Probably, it seems that the package is not enough.
Please install the following package and try building again.
```
sudo apt-get install ros-indigo-dynamic-edt-3d
```
