### ISSUE TITLE
import error in python

### ISSUE THREAD

**Issue by 1075976432** [neka-nat/python-octomap#8]
When  importing octomap in python, there is a error shown below. 
```
ImportError: libdynamicedt3d.so.1.8: cannot open shared object file: No such file or directory
```
I built with the command line:
```
python setup.py build_ext --include-dirs /usr/local/include/octomap --library-dirs /usr/local/lib/
```
And after the installation ,the result was:
```
running install
running build
running build_py
package init file 'octomap/__init__.py' not found (or not a regular file)
package init file 'octomap/__init__.py' not found (or not a regular file)
running build_ext
skipping 'octomap/octomap.cpp' Cython extension (up-to-date)
running install_lib
copying build/lib.linux-x86_64-2.7/octomap.so -> /usr/local/lib/python2.7/dist-packages
running install_egg_info
Removing /usr/local/lib/python2.7/dist-packages/octomap-0.5.egg-info
Writing /usr/local/lib/python2.7/dist-packages/octomap-0.5.egg-info
```
I wonder how to solve this problem??
Thanks!

**Comment by neka-nat** [comment]
Hi @1075976432,
It seems that Dynamicedt3d library is not installed.
If you use Ubuntu, try install the following library.
```
sudo apt-get install libdynamicedt3d-dev
```
or
```
sudo apt-get install ros-mellodic-dynamic-edt-3d
```

**Comment by icoderaven** [comment]
If you notice the ldd output when using build_ext, the issue is that the build_ext process tries to find the external libraries in the system LD_LIBRARY_PATH, whereas they've been installed to your local install path.

The correct solution would be to add the external install library directory to the rpath when building, so in your case
```
 python setup.py build_ext --include-dirs /usr/local/include/octomap --library-dirs /usr/local/lib/ --rpath /usr/local/lib
```
